/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2019-04-22 14:50:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1536948270000L));
    _jspx_dependants.put("jar:file:/G:/EclipsePhotonWorkArray/jee-photon/ZCYL/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" 
				+ request.getServerPort() + path + "/";
	application.setAttribute("basePath", path);

      out.write("\r\n");
      out.write("<html lang=\"en\"><head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.SYSNAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/login/bootstrap.css\">\r\n");
      out.write("    <link href=\"static/ryn/auth.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"auth\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <form class=\"form-signin\" action=\"\" method=\"post\" name=\"loginForm\" id=\"loginForm\">\r\n");
      out.write("            <img class=\"img logo-img\" src=\"static/assets/images/logo.png\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span>中朝友联旅游</span>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"margin-bottom:5px;\">\r\n");
      out.write("                <input name=\"loginname\" type=\"text\" class=\"form-control\" id=\"loginname\" placeholder=\"用户名\" maxlength=\"20\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"margin-bottom:5px;\">\r\n");
      out.write("                <input id=\"password\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"密码\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("            \t<input id=\"code\" type=\"text\" class=\"form-control\" name=\"code\" placeholder=\"验证码\">\r\n");
      out.write("                <span class=\"input-group-addon\"><img style=\"height:22px;\" id=\"codeImg\" alt=\"点击更换\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"点击更换\" src=\"\" />\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("            <a id=\"loginBtn\" class=\"btn btn-large btn-primary\" onclick=\"severCheck();\" >登&nbsp; &nbsp; &nbsp;&nbsp; 录</a>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- javscript js -->\r\n");
      out.write("<script src=\"static/login/jquery.js\"></script>\r\n");
      out.write("<script src=\"static/login/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery.cookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//服务器校验\r\n");
      out.write("\tfunction severCheck(){\r\n");
      out.write("\t\tif(check()){\t\t\t\t\r\n");
      out.write("\t\t\tvar loginname = $(\"#loginname\").val();\r\n");
      out.write("\t\t\tvar password = $(\"#password\").val();\r\n");
      out.write("\t\t\tvar code = \"RC03030514\"+loginname+\",R3C5,\"+password+\"19881994NH\" + \",R3C5,\" + $(\"#code\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: 'login_login',\r\n");
      out.write("\t\t    \tdata: {KEYDATA:code,tm:new Date().getTime()},\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tcache: false,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tif(\"success\" == data.result){\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tsaveCookie();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"main/index\";\r\n");
      out.write("\t\t\t\t\t}else if(\"usererror\" == data.result){\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginname\").tips({\r\n");
      out.write("\t\t\t\t\t\t\tside : 1,\r\n");
      out.write("\t\t\t\t\t\t\tmsg : \"用户名或密码有误\",\r\n");
      out.write("\t\t\t\t\t\t\tbg : '#FF5080',\r\n");
      out.write("\t\t\t\t\t\t\ttime : 5\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginname\").focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"codeerror\" == data.result)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t$(\"#code\").tips({\r\n");
      out.write("\t\t\t\t\t\t\tside : 1,\r\n");
      out.write("\t\t\t\t\t\t\tmsg : \"验证码输入有误\",\r\n");
      out.write("\t\t\t\t\t\t\tbg : '#FF5080',\r\n");
      out.write("\t\t\t\t\t\t\ttime : 5\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#code\").focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"stateerror\" == data.result){\r\n");
      out.write("\t\t\t\t\t\talert(\"该用户被禁止了!\");\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginname\").tips({\r\n");
      out.write("\t\t\t\t\t\t\tside : 1,\r\n");
      out.write("\t\t\t\t\t\t\tmsg : \"缺少参数\",\r\n");
      out.write("\t\t\t\t\t\t\tbg : '#FF5080',\r\n");
      out.write("\t\t\t\t\t\t\ttime : 5\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginname\").focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tchangeCode();\r\n");
      out.write("\t\t$(\"#codeImg\").bind(\"click\", changeCode);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).keyup(function(event) {\r\n");
      out.write("\t\tif (event.keyCode == 13) {\r\n");
      out.write("\t\t\t$(\"#loginBtn\").trigger(\"click\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction genTimestamp() {\r\n");
      out.write("\t\tvar time = new Date();\r\n");
      out.write("\t\treturn time.getTime();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeCode() {\r\n");
      out.write("\t\t$(\"#codeImg\").attr(\"src\", \"code?t=\" + genTimestamp());\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//客户端校验\r\n");
      out.write("\tfunction check() {\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#loginname\").val() == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#loginname\").tips({\r\n");
      out.write("\t\t\t\tside : 2,\r\n");
      out.write("\t\t\t\tmsg : '用户名不得为空',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#loginname\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#loginname\").val(jQuery.trim($('#loginname').val()));\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#password\").val() == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#password\").tips({\r\n");
      out.write("\t\t\t\tside : 2,\r\n");
      out.write("\t\t\t\tmsg : '密码不得为空',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ($(\"#code\").val() == \"\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#code\").tips({\r\n");
      out.write("\t\t\t\tside : 3,\r\n");
      out.write("\t\t\t\tmsg : '验证码不得为空',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#code\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#loginbox\").tips({\r\n");
      out.write("\t\t\tside : 1,\r\n");
      out.write("\t\t\tmsg : '正在登录 , 请稍后 ...',\r\n");
      out.write("\t\t\tbg : '#68B500',\r\n");
      out.write("\t\t\ttime : 10\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction savePaw() {\r\n");
      out.write("\t\tif (!$(\"#saveid\").attr(\"checked\")) {\r\n");
      out.write("\t\t\t$.cookie('loginname', '', {\r\n");
      out.write("\t\t\t\texpires : -1\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.cookie('password', '', {\r\n");
      out.write("\t\t\t\texpires : -1\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#loginname\").val('');\r\n");
      out.write("\t\t\t$(\"#password\").val('');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction saveCookie() {\r\n");
      out.write("\t\tif ($(\"#saveid\").attr(\"checked\")) {\r\n");
      out.write("\t\t\t$.cookie('loginname', $(\"#loginname\").val(), {\r\n");
      out.write("\t\t\t\texpires : 7\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.cookie('password', $(\"#password\").val(), {\r\n");
      out.write("\t\t\t\texpires : 7\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction quxiao() {\r\n");
      out.write("\t\t$(\"#loginname\").val('');\r\n");
      out.write("\t\t$(\"#password\").val('');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(function() {\r\n");
      out.write("\t\tvar loginname = $.cookie('loginname');\r\n");
      out.write("\t\tvar password = $.cookie('password');\r\n");
      out.write("\t\tif (typeof(loginname) != \"undefined\" && typeof(password) != \"undefined\") {\r\n");
      out.write("\t\t\t$(\"#loginname\").val(loginname);\r\n");
      out.write("\t\t\t$(\"#password\").val(password);\r\n");
      out.write("\t\t\t$(\"#saveid\").attr(\"checked\", true);\r\n");
      out.write("\t\t\t$(\"#code\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tif (window != top) {\r\n");
      out.write("           top.location.href = \"");
      out.print(basePath);
      out.write("login\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
