/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2019-06-13 14:00:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.art;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slide_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/G:/EclipsePhotonWorkArray/jee-photon/ZCYL/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/system/art/../index/foot.jsp", Long.valueOf(1534542862000L));
    _jspx_dependants.put("jar:file:/G:/EclipsePhotonWorkArray/jee-photon/ZCYL/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/system/art/../index/top.jsp", Long.valueOf(1544232589518L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1536948270000L));
    _jspx_dependants.put("jar:file:/G:/EclipsePhotonWorkArray/jee-photon/ZCYL/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/ace/css/chosen.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.SYSNAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\t\t<!-- bootstrap & fontawesome -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ace/css/bootstrap.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ace/css/font-awesome.css\" />\r\n");
      out.write("\t\t<!-- page specific plugin styles -->\r\n");
      out.write("\t\t<!-- text fonts -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ace/css/ace-fonts.css\" />\r\n");
      out.write("\t\t<!-- ace styles -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ace/css/ace.css\" class=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ryn/auth.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ryn/navbar.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ryn/breadcrumbs.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ryn/modal.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/ryn/main.css\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if lte IE 9]>\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"static/ace/css/ace-part2.css\" class=\"ace-main-stylesheet\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<!--[if lte IE 9]>\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"static/ace/css/ace-ie.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<!-- inline styles related to this page -->\r\n");
      out.write("\t\t<!-- ace settings handler -->\r\n");
      out.write("\t\t<script src=\"static/ace/js/ace-extra.js\"></script>\r\n");
      out.write("\t\t<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->\r\n");
      out.write("\t\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t<script src=\"static/ace/js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/ace/js/respond.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/ace/css/datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/global/css/mycomponents.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/global/plugins/jstree/dist/themes/default/style.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"static/global/css/plugins.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".btn.btn-app.btn-xs {\r\n");
      out.write("\twidth: 64px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tpadding-bottom: 2px;\r\n");
      out.write("\tpadding-top: 2px;\r\n");
      out.write("\tline-height: 1.45;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<head></head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"page-header\">\r\n");
      out.write("\t\t<ul class=\"navi\">\r\n");
      out.write("\t\t\t<li><a>艺术商品管理</a><span> ≫ </span></li>\r\n");
      out.write("\t\t\t<li><a target=\"mainFrame\" href=\"sa/listSlide\">横幅管理</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page-content\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t                <td class=\"ipt-td\">简介</td>\r\n");
      out.write("\t                <td class=\"ipt-td\">\r\n");
      out.write("\t\t\t\t    \t<input class=\"form-control\" id=\"S_DESC\" type=\"text\">\r\n");
      out.write("\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t    <td class=\"ipt-td\">\r\n");
      out.write("\t\t\t\t    \t<button onclick=\"initCtrl();\" class=\"btn btn-primary\">重置</button>\r\n");
      out.write("\t\t\t    \t</td>\r\n");
      out.write("\t\t\t  \t</tr>\r\n");
      out.write("\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t  \t\t<td class=\"ipt-td\">状态</td>\r\n");
      out.write("\t                <td class=\"ipt-td\">\r\n");
      out.write("\t\t\t\t    \t<select id=\"S_STATE\" class=\"form-control\" style=\"margin-bottom:5px;\">\r\n");
      out.write("    \t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("\t\t\t\t\t\t    <option value=\"1\">已显示</option>\r\n");
      out.write("\t\t\t\t\t\t    <option value=\"0\">未显示</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t    </td>\r\n");
      out.write("\t\t\t    \t<td class=\"ipt-td\">\r\n");
      out.write("\t            \t\t<button type=\"button\" onclick=\"search();\" class=\"btn btn-primary\">查询</button>\r\n");
      out.write("\t            \t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ipt-td\">\r\n");
      out.write("\t            \t\t<button type=\"button\" onclick=\"addSlide();\" class=\"btn btn-primary\">新增</button>\r\n");
      out.write("\t            \t</td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<form action=\"sa/listSlide\" method=\"post\" name=\"saSlideForm\" id=\"saSlideForm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table id=\"simple-table\" class=\"table table-hover\" style=\"margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\" style=\"width: 50px;\">序号</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\" style=\"width: 80px;\">缩略图</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\" style=\"width: 120px;\">简介</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\" style=\"width: 50px;\">状态</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\" style=\"width: 100px;\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /WEB-INF/jsp/system/art/slide_list.jsp(89,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty slideList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t");

						            int numStds = 0;								
						            pageContext.setAttribute("numStds", numStds);
						        
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t");
                  //  c:forEach
                  org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
                  boolean _jspx_th_c_005fforEach_005f0_reused = false;
                  try {
                    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
                    // /WEB-INF/jsp/system/art/slide_list.jsp(94,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
                    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/system/art/slide_list.jsp(94,8) '${slideList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${slideList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
                    // /WEB-INF/jsp/system/art/slide_list.jsp(94,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_c_005fforEach_005f0.setVar("sl");
                    // /WEB-INF/jsp/system/art/slide_list.jsp(94,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
                    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
                    try {
                      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
                      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        do {
                          out.write("\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t");

							            numStds++;								
							            pageContext.setAttribute("numStds", numStds);
							        
                          out.write("\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t<tr id=\"row_");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("\">\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(page.currentPage -1) * page.showCount + numStds}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</td>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<!--<td class=\"center sl-name\">");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</td>-->\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"center sl-name\">\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t<img style=\"width: 120px; height: 40px;\" alt=\"\" src=\"uploadFiles/uploadImgs/sa/");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("\"></td>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"center sl-desc\">");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.comment }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</td>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"center sl-state\">");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.state == 1 ? '已显示' : '未显示'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("</td>\t\t\t\t\t\t\t\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"center\">\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-minier btn-white btn_m_edit\"\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"updateSlide('");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.view_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("');\">编辑</a>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-minier btn-white btn_m_delete\"\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"delSlide('");
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write('\'');
                          out.write(',');
                          out.write('\'');
                          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sl.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                          out.write("');\">删除</a>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
                          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
                          out.write("\t\t\t\t\t\t\t\t");
                          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                      }
                      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        return;
                      }
                    } catch (java.lang.Throwable _jspx_exception) {
                      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
                        out = _jspx_page_context.popBody();
                      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
                    } finally {
                      _jspx_th_c_005fforEach_005f0.doFinally();
                    }
                    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
                    _jspx_th_c_005fforEach_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
                  }
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"vertical-align: top;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pagination\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"float: left; padding-top: 0px; margin-top: 0px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pageStr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"slideModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"slideModalLabel\">\t\t\t\t\t\t\r\n");
      out.write("\t\t  \t\t<div class=\"modal-dialog\" role=\"document\" style=\"width:500px\">\r\n");
      out.write("\t\t    \t\t<div class=\"modal-content\" style=\"border-width:0px;\">\r\n");
      out.write("\t\t      \t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t        \t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t        \t\t\t\t<span aria-hidden=\"true\">&times;</saan></button>\r\n");
      out.write("\t\t        \t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\" style=\"font-weight:bold\">新增横幅</h4>\r\n");
      out.write("\t\t      \t\t\t</div>\r\n");
      out.write("\t\t      \t\t\t<div class=\"modal-body\" style=\"text-align:left;\">\r\n");
      out.write("\t\t      \t\t\t\t<input id=\"SLIDE_ID\" type=\"text\" style=\"display:none;\" value=\"\">\r\n");
      out.write("\t\t      \t\t\t\t<table>\r\n");
      out.write("\t\t      \t\t\t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td class=\"ipt-td\">图片</td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t<input type=\"file\" id=\"SLIDE_IMAGE\" name=\"SLIDE_IMAGE\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: none;\" onchange=\"uploadFile(this)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"fileType('SLIDE_IMAGE')\" id=\"SLIDE_IMAGE_BTN\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-mini btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"margin-bottom:5px; height: 30px; align: center;\">选择文件</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img id=\"SLIDE_IMAGE_PREVIEW\" alt=\"\" src=\"\" style=\"height: 45px; max-width:230px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"SLIDE_IMAGE_NAME\" id=\"SLIDE_IMAGE_NAME\" accept=\"image/*\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"32\" placeholder=\"来选择任何文件\" title=\"图片\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: none;\"/>\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t</tr>\r\n");
      out.write("\t\t      \t\t\t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td class=\"ipt-td\">简介</td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t<textarea id=\"SLIDE_DESC\" class=\"form-control\" rows=\"5\" style=\"min-width:400px;max-width:400px;\"></textarea>\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t</tr>\r\n");
      out.write("\t\t      \t\t\t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <label><input id=\"SLIDE_VIEW_STATE\" type=\"checkbox\" value=\"\" style=\"margin-bottom:5px;\">是否显示</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t</tr>\r\n");
      out.write("\t\t      \t\t\t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td class=\"ipt-td\">\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t展示格式\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t<select id=\"SLIDE_VIEW_TYPE\" class=\"form-control\" style=\"margin-bottom:5px;\">\r\n");
      out.write("\t\t      \t\t\t\t\t\t\t\t<option value=\"\">请选择</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <option value=\"1\">中心</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <option value=\"2\">适合宽度</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <option value=\"3\">适合高度</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t      \t\t\t\t\t\t</td>\r\n");
      out.write("\t\t      \t\t\t\t\t\t<td><span style=\"color:red;\">*</span></td>\r\n");
      out.write("\t\t      \t\t\t\t\t</tr>\r\n");
      out.write("\t\t      \t\t\t\t\t\r\n");
      out.write("\t\t      \t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t      \t\t</div>\r\n");
      out.write("\t\t      \t\t<div class=\"modal-footer\" style=\"padding: 5px 0px 10px 0px;\">\r\n");
      out.write("\t\t      \t\t\t<button type=\"button\" class=\"btn btn-primary btn_user_modal_confirm\" onclick=\"slideConfirm();\">确定</button>\r\n");
      out.write("\t        \t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">取消</button>\t\t\t\t\t        \r\n");
      out.write("\t\t      \t\t</div>\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" id=\"btn-scroll-up\"\r\n");
      out.write("\t\tclass=\"btn-scroll-up btn btn-sm btn-inverse\"> <i\r\n");
      out.write("\t\tclass=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t");
      out.write('	');
      out.write('	');

			String pathf = request.getContextPath();
			String basePathf = request.getScheme() + "://"
					+ request.getServerName() + ":" + request.getServerPort()
					+ pathf + "/";
		
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.jQuery || document.write(\"<script src='");
      out.print(basePathf);
      out.write("static/ace/js/jquery.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- <![endif]-->\r\n");
      out.write("\t\t<!--[if IE]>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t window.jQuery || document.write(\"<script src='");
      out.print(basePathf);
      out.write("static/ace/js/jquery1x.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif('ontouchstart' in document.documentElement) document.write(\"<script src='");
      out.print(basePathf);
      out.write("static/ace/js/jquery.mobile.custom.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"static/ace/js/bootstrap.js\"></script>");
      out.write("\r\n");
      out.write("\t<script src=\"static/ace/js/bootbox.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"static/ace/js/ace/ace.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"static/ace/js/date-time/bootstrap-datepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"static/ace/js/chosen.jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(function() {\r\n");
      out.write("\t\t$(\"#S_DESC\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.COMMENT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t\t$(\"#S_STATE\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.STATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction initCtrl(){\r\n");
      out.write("\t\t$(\"#S_DESC\").val('');\r\n");
      out.write("\t\t$(\"#S_STATE\").val('');\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction search(){\r\n");
      out.write("\t\tvar DESC = $(\"#S_DESC\").val();\r\n");
      out.write("\t\tvar STATE = $(\"#S_STATE\").val();\r\n");
      out.write("\t\t$(\"#saSlideForm\").attr(\"action\", \"sa/listSlide/?COMMENT=\" + DESC + \"&STATE=\" + STATE);\r\n");
      out.write("\t\t$(\"#saSlideForm\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction fileType(file) {\r\n");
      out.write("\t\tdocument.getElementById(file).click();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction uploadFile(obj) {\r\n");
      out.write("\t\t$(\"#SLIDE_IMAGE_NAME\").val(obj.files[0].name);\r\n");
      out.write("\t\tvar fileType = obj.value.substr(obj.value.lastIndexOf(\".\"))\r\n");
      out.write("\t\t\t\t.toLowerCase();//获得文件后缀名\r\n");
      out.write("\t\tif (fileType != '.jpg' && fileType != '.png' && fileType != '.bmp') {\r\n");
      out.write("\t\t\t$(\"#SLIDE_IMAGE_NAME\").tips({\r\n");
      out.write("\t\t\t\tside : 3,\r\n");
      out.write("\t\t\t\tmsg : '请上传图片格式的文件',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#SLIDE_IMAGE_NAME\").val('');\r\n");
      out.write("\t\t\tdocument.getElementById(\"SLIDE_IMAGE\").files[0] = '请选择图片格式的文件';\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.each(obj.files, function(_, file) {\r\n");
      out.write("\t        var reader = new FileReader();\r\n");
      out.write("\t        reader.onload = function (ev) {\r\n");
      out.write("\t        \t$(\"#SLIDE_IMAGE_PREVIEW\").attr('src', ev.target.result);\r\n");
      out.write("\t        }\r\n");
      out.write("\t        reader.readAsDataURL(file);\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction slideConfirm(){\r\n");
      out.write("\t\tvar _id = $(\"#SLIDE_ID\").val();\r\n");
      out.write("\t\tvar _name = $(\"#SLIDE_IMAGE_NAME\").val();\r\n");
      out.write("\t\tvar _vstate = $(\"#SLIDE_VIEW_STATE\").prop('checked') == true ? 1 : 0;\r\n");
      out.write("\t\tvar _vtype = $(\"#SLIDE_VIEW_TYPE\").val();\r\n");
      out.write("\t\tvar _desc = $(\"#SLIDE_DESC\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(_name == \"\"){\r\n");
      out.write("\t\t\t$(\"#SLIDE_IMAGE_BTN\").tips({\r\n");
      out.write("\t\t\t\tside : 2,\r\n");
      out.write("\t\t\t\tmsg : '请选择图片',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#SLIDE_IMAGE_BTN\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(_vtype == \"\"){\r\n");
      out.write("\t\t\t$(\"#SLIDE_VIEW_TYPE\").tips({\r\n");
      out.write("\t\t\t\tside : 2,\r\n");
      out.write("\t\t\t\tmsg : '请选择展示格式',\r\n");
      out.write("\t\t\t\tbg : '#AE81FF',\r\n");
      out.write("\t\t\t\ttime : 3\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#SLIDE_VIEW_TYPE\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar fd = new FormData();\r\n");
      out.write("\t    var _img = $('#SLIDE_IMAGE')[0].files;\r\n");
      out.write("\t    \r\n");
      out.write("\t    fd.append(\"ID\", _id);\r\n");
      out.write("\t    fd.append(\"IMG_NAME\", _name);\r\n");
      out.write("\t \tfd.append(\"COMMENT\", _desc);\r\n");
      out.write("\t\tfd.append(\"VIEW_STATE\", _vstate);\r\n");
      out.write("\t\tfd.append(\"VIEW_TYPE\", _vtype);\r\n");
      out.write("\t\tfd.append(\"IMG\", _img[0]);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttop.jzts();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: '");
      out.print(basePath);
      out.write("sa/saveSlide',\r\n");
      out.write("\t    \tdata: fd,\r\n");
      out.write("\t    \tcontentType: false,\r\n");
      out.write("       \t \tprocessData: false,\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tif(\"success\" == data.result){\r\n");
      out.write("\t\t\t\t\t$('#slideModal').modal(\"hide\");\r\n");
      out.write("\t\t\t\t\tsearch();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert('FAILED!');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(top.hangge());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addSlide(){\r\n");
      out.write("\t\t$(\"#SLIDE_ID\").val(\"\");\r\n");
      out.write("\t\t$(\"#SLIDE_IMAGE_NAME\").val(\"\");\r\n");
      out.write("\t\t$(\"#SLIDE_IMAGE_PREVIEW\").attr('src', '');\r\n");
      out.write("\t\t$(\"#SLIDE_VIEW_STATE\").attr(\"checked\", true);\r\n");
      out.write("\t\t$(\"#SLIDE_VIEW_TYPE\").val(\"\");\r\n");
      out.write("\t\t$(\"#SLIDE_DESC\").val(\"\");\r\n");
      out.write("\t\t$('#slideModal').modal(\"show\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#myModalLabel\").html(\"新增横幅\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateSlide(_id, _name, _desc, _vType, _vState){\r\n");
      out.write("\t\t$(\"#myModalLabel\").html(\"编辑横幅\");\r\n");
      out.write("\t\t$(\"#SLIDE_ID\").val(_id);\r\n");
      out.write("\t\t$(\"#SLIDE_IMAGE_NAME\").val(_name);\r\n");
      out.write("\t\t$(\"#SLIDE_IMAGE_PREVIEW\").attr('src', \"uploadFiles/uploadImgs/sa/\" + _name);\r\n");
      out.write("\t\t_vState == 1 ?  $(\"#SLIDE_VIEW_STATE\").attr(\"checked\", true) : $(\"#SLIDE_VIEW_STATE\").attr(\"checked\", false); \r\n");
      out.write("\t\t$(\"#SLIDE_VIEW_TYPE\").val(_vType);\r\n");
      out.write("\t\t$(\"#SLIDE_DESC\").val(_desc);\r\n");
      out.write("\t\t$('#slideModal').modal(\"show\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction delSlide(_id, _comment, _name){\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\t\tmessage: \"<div class='item-row'><div class='item-label'>横幅名称 :</div>\" + \r\n");
      out.write("\t\t\t\t\t\t \"<div class='item-value'>\" + _comment + \"</div></div>\" +\r\n");
      out.write("\t\t\t\t\t\t \"<div class='item-row'><div class='item-info'>您确定删除吗?</div></div>\",\r\n");
      out.write("\t\t\t\ttitle: \"删除横幅\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbootbox.confirm(options, function(result) {\r\n");
      out.write("\t\t\tif(result) {\r\n");
      out.write("\t\t\t\ttop.jzts();\r\n");
      out.write("\t\t\t\tvar url = \"");
      out.print(basePath);
      out.write("sa/deleteSlide?ID=\" + _id + \"&NAME=\" + _name;\r\n");
      out.write("\t\t\t\t$.get(url,function(data){\r\n");
      out.write("\t\t\t\t\tif(data.result == \"success\")\r\n");
      out.write("\t\t\t\t\t\tsearch();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(top.hangge());\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
